### ISSUE TITLE
shasum discrepancy for genesis.json

### ISSUE THREAD

**Issue by janeymunoz** [cosmos/mainnet#142]
The [latest readme](https://github.com/cosmos/mainnet/blob/a4a7c632ef681d0aa7c7e394c5c7d2c439e9b943/README.md#cosmos-hub-launch) seems to have a discrepancy, regarding the shasum of the recommended genesis file.

The readme states:

> The recommended genesis file is [genesis.json](https://raw.githubusercontent.com/cosmos/launch/master/genesis.json). It has the
following SHA256 hash:
>
>```
>$ shasum -a 256 genesis.json 
>73a866b21723ecbc28b6d15951b2eb3aa2f2443650ff6df489bf55ac5edceefa  genesis.json
>$ b2sum genesis.json 
>8c90b58efe9e0959953fe27ba431137c24c514e357b8025f5252c85ea7401247a909fac9531>3b907bb48579c6e389b4bbf06df626bff19aae554028964fa189d  genesis.json
>```

But I am seeing:

```
$ curl -o genesis.json https://raw.githubusercontent.com/cosmos/launch/master/genesis.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60.1M  100 60.1M    0     0  46.2M      0  0:00:01  0:00:01 --:--:-- 46.2M
$ shasum -a 256 genesis.json
5c2e311745a4cd3cfb4eaa7a7dace4cc116500ee65395b583444add9e72e1d1a  genesis.json
```

However, when I follow the [instructions for regenerating the genesis file](https://github.com/cosmos/mainnet/blob/a4a7c632ef681d0aa7c7e394c5c7d2c439e9b943/GENESIS.md#regenerating-the-genesis-file), I *do* get the same shasum as that shown in the readme.

**Comment by agus-xyz** [comment]
I am also confused about this...
