### ISSUE TITLE
0x address to cosmos address

### ISSUE THREAD

**Issue by johnsac** [cosmos/mainnet#9]
Using the Fundraiser tool found here (https://fundraiser.cosmos.network/), I have a cosmos address beginning in 0x.  How do we convert these to see verify our cosmos address in the genesis file?

**Comment by zmanian** [comment]
The recommended way is to use the procedure from the delegator guide.
https://github.com/cosmos/cosmos-sdk/blob/master/docs/gaia/delegator-guide-cli.md#restoring-an-account-from-the-fundraiser

A slightly less user friendly way but doesn't require going back and forth from an airgapped computer or a ledger is to use the gaiadebug tool in https://github.com/cosmos/cosmos-sdk/tree/develop/cmd/gaia/cmd/gaiadebug

build the tool and `./gaiadebug addr [hex] address` and it will spit out the bech32 encoding.
